### ISSUE TITLE
Java memory issues

### ISSUE THREAD

**Issue by keirballa** [gFedonin/VirGenA#1]
Hi Gennady,

I am trying to run VirGenA on a cluster but have been running in to Java memory errors (both heap space and GC overhead limits exceeded). The trial data run fine. For the experimental data I am running against a single reference with paired-end reads that do not map to the host genome. The number of reads that should map to the virus genome are a small fraction of the total (expected to be ~500-1000 reads out of 20million). Is the low mapping rate an issue here?

-Keir

**Comment by gFedonin** [comment]
VirGenA should treat low mapping rates fine. Can you give it more memory? It should generally fit in  4*sizeof(total reads size + reference). Just sequences of 20 mln paired reads of length 150 is 6 Gb, so you might need about 24 GB RAM.

**Comment by keirballa** [comment]
Increasing memory to 64GB allowed it to complete, but the only output was
the following in the log file:

"Creating random reads model from reference with the parameters given in
the config file in <RandomModelParameters>
Iteration 1"


It seems to give up after that. The run also seems to contain some java
errors:

java.lang.NegativeArraySizeException
at StringIndexer.buildIndexPara(StringIndexer.java:48)
at Reference.<init>(Reference.java:261)
at RandomModel.<init>(RandomModel.java:37)
at KMerCounter.<init>(KMerCounter.java:29)
at KMerCounter.getInstance(KMerCounter.java:59)
at Mapper.<init>(Mapper.java:29)
at ConsensusBuilderSimple.<init>(ConsensusBuilderSimple.java:23)
at
ConsensusBuilderWithReassembling.<init>(ConsensusBuilderWithReassembling.java:41)
at RefBasedAssembler.run(RefBasedAssembler.java:665)
at VirGenA.main(VirGenA.java:34)
java.lang.IllegalArgumentException
at
java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
at
java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1202)
at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:89)
at RandomModel.genRandomScores(RandomModel.java:132)
at RandomModel.genModel(RandomModel.java:102)
at KMerCounter.<init>(KMerCounter.java:40)
at KMerCounter.getInstance(KMerCounter.java:59)
at Mapper.<init>(Mapper.java:29)
at ConsensusBuilderSimple.<init>(ConsensusBuilderSimple.java:23)
at
ConsensusBuilderWithReassembling.<init>(ConsensusBuilderWithReassembling.java:41)
at RefBasedAssembler.run(RefBasedAssembler.java:665)
at VirGenA.main(VirGenA.java:34)
java.lang.NegativeArraySizeException
at StringIndexer.buildIndexPara(StringIndexer.java:48)
at Reference.<init>(Reference.java:106)
at
ConsensusBuilderWithReassembling.assemble(ConsensusBuilderWithReassembling.java:763)
at RefBasedAssembler.run(RefBasedAssembler.java:666)
at VirGenA.main(VirGenA.java:34)
java.lang.IllegalArgumentException
at
java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
at
java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1202)
at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:89)
at Mapper.mapReads(Mapper.java:437)
at
ConsensusBuilderWithReassembling.buildConsensus(ConsensusBuilderWithReassembling.java:332)
at
ConsensusBuilderWithReassembling.assemble(ConsensusBuilderWithReassembling.java:765)
at RefBasedAssembler.run(RefBasedAssembler.java:666)
at VirGenA.main(VirGenA.java:34)
java.lang.NullPointerException
at
ConsensusBuilderWithReassembling.assemble(ConsensusBuilderWithReassembling.java:766)
at RefBasedAssembler.run(RefBasedAssembler.java:666)
at VirGenA.main(VirGenA.java:34)


Here is my configuration in case that helps:

<config>
    <Data>
        <pathToReads1>./unmapped_1.fq.gz</pathToReads1>
        <pathToReads2>./unmapped_2.fq.gz</pathToReads2>
        <InsertionLength>1000</InsertionLength>
    </Data>
    <Reference>./PV_1.fa</Reference>
    <OutPath>./VirGenA_out/</OutPath>
    <ThreadNumber>-6</ThreadNumber>
<BatchSize>1000</BatchSize>
    <ReferenceSelector>
<Enabled>false</Enabled>
        <UseMajor>false</UseMajor>
        <ReferenceMSA>Path to reference MSA in FASTA format</ReferenceMSA>
        <PathToUsearch>Path to vsearch executable</PathToUsearch>
        <UclustIdentity>0.95</UclustIdentity>
        <MinReadLength>50</MinReadLength>
        <MinContigLength>1000</MinContigLength>
        <Delta>0.05</Delta>
<MaxNongreedyComponentNumber>5</MaxNongreedyComponentNumber>
        <MapperToMSA>
<K>7</K>
<pValue>0.01</pValue>
<IndelToleranceThreshold>1.5</IndelToleranceThreshold>
<RandomModelParameters>
<Order>4</Order>
<ReadNum>10000</ReadNum>
<Step>10</Step>
</RandomModelParameters>
        </MapperToMSA>
        <Graph>
            <MinReadNumber>5</MinReadNumber>
            <VertexWeight>10</VertexWeight>
<SimilarityThreshold>0.5</SimilarityThreshold>
<Debug>false</Debug>
        </Graph>
        <Debug>false</Debug>
    </ReferenceSelector>
    <Mapper>
<K>5</K>
        <pValue>0.01</pValue>
<IndelToleranceThreshold>1.25</IndelToleranceThreshold>
<RandomModelParameters>
<Order>4</Order>
<ReadNum>1000</ReadNum>
<Step>10</Step>
</RandomModelParameters>
        <Aligner>
            <Match>2</Match>
            <Mismatch>-3</Mismatch>
            <GapOpenPenalty>5</GapOpenPenalty>
            <GapExtensionPenalty>2</GapExtensionPenalty>
        </Aligner>
    </Mapper>
    <ConsensusBuilder>
        <IdentityThreshold>0.9</IdentityThreshold>
        <CoverageThreshold>0</CoverageThreshold>
        <MinIntersectionLength>10</MinIntersectionLength>
        <MinTerminationReadsNumber>1</MinTerminationReadsNumber>
<Reassembler>
<IdentityThreshold>0.9</IdentityThreshold>
<MinTerminatingSequenceCoverage>0</MinTerminatingSequenceCoverage>
<PairReadTerminationThreshold>0.1</PairReadTerminationThreshold>
<MinReadLength>50</MinReadLength>
</Reassembler>
<Debug>false</Debug>
    </ConsensusBuilder>
    <Postprocessor>
        <Enabled>true</Enabled>
        <MinFragmentLength>500</MinFragmentLength>
        <MinIdentity>0.99</MinIdentity>
<MinFragmentCoverage>0.99</MinFragmentCoverage>
        <Debug>false</Debug>
    </Postprocessor>
</config>

**Comment by gFedonin** [comment]
Hi, Keir!

The problem might be because of ThreadNumber = -6.
This field, number of threads, should be positive integer or -1, which means "use all cores". I will update documentation and add some parameters' checks in future releases.

By the way, thank you for using our tool! I hope you'll find it usefull. You can ask any questions here or write me an email if you like.
