### ISSUE TITLE
virGenA run for viral genome database

### ISSUE THREAD

**Issue by Anupriya014** [gFedonin/VirGenA#4]
Dear Gennady G. Fedonin,

Greetings of the day!

I am trying to run virGenA with a sample (paired-end .fastq.gz files) with a viral database (multi FASTA file).
As 1st step, I tried creating MSA fasta file for the database using T-coffee tool but it failed -- sequence lengths were too long for algorithm.
So I disabled the reference selector but virGenA kept running without outputting any file (memory used 350gb).
I am stuck at this stage. Please help me out. And is there any way to make MSA FASTA (with/without using MSA tool)?

Command & config file used -

`nohup java -Xmx350g -jar /home/softwares/virgenA_release_v1.4/VirGenA.jar assemble -c ./config1.xml`

`<config>
    <Data>
        <pathToReads1>./5x_R1_clean.fastq.gz</pathToReads1>
        <pathToReads2>./5x_R2_clean.fastq.gz</pathToReads2>
        <InsertionLength>1000</InsertionLength>
    </Data>
    <Reference>/home/phase_2/viruSITE/viruSITE_genomes.fasta</Reference>
    <OutPath>./out</OutPath>
    <ThreadNumber>-1</ThreadNumber>
	<BatchSize>1000</BatchSize>
    <ReferenceSelector>
	<Enabled>false</Enabled>
        <UseMajor>false</UseMajor>
        <ReferenceMSA>Path to reference MSA in FASTA format</ReferenceMSA>
        <PathToUsearch>/home/softwares/virgenA_release_v1.4/tools/vsearch</PathToUsearch>
        <UclustIdentity>0.95</UclustIdentity>
        <MinReadLength>50</MinReadLength>
        <MinContigLength>1000</MinContigLength>
        <Delta>0.05</Delta>
		<MaxNongreedyComponentNumber>5</MaxNongreedyComponentNumber>
        <MapperToMSA>
			<K>7</K>
			<pValue>0.01</pValue>
			<IndelToleranceThreshold>1.5</IndelToleranceThreshold>
			<RandomModelParameters>
				<Order>4</Order>
				<ReadNum>10000</ReadNum>
				<Step>10</Step>
			</RandomModelParameters>
        </MapperToMSA>
        <Graph>
            <MinReadNumber>5</MinReadNumber>
            <VertexWeight>10</VertexWeight>
			<SimilarityThreshold>0.5</SimilarityThreshold>
			<Debug>false</Debug>
        </Graph>
        <Debug>false</Debug>
    </ReferenceSelector>
    <Mapper>
		<K>5</K>
        <pValue>0.01</pValue>
		<IndelToleranceThreshold>1.25</IndelToleranceThreshold>
		<RandomModelParameters>
			<Order>4</Order>
			<ReadNum>1000</ReadNum>
			<Step>10</Step>
		</RandomModelParameters>
        <Aligner>
            <Match>2</Match>
            <Mismatch>-3</Mismatch>
            <GapOpenPenalty>5</GapOpenPenalty>
            <GapExtensionPenalty>2</GapExtensionPenalty>
        </Aligner>
    </Mapper>
    <ConsensusBuilder>
        <IdentityThreshold>0.9</IdentityThreshold>
        <CoverageThreshold>0</CoverageThreshold>
        <MinIntersectionLength>10</MinIntersectionLength>
        <MinTerminationReadsNumber>1</MinTerminationReadsNumber>
		<Reassembler>
			<IdentityThreshold>0.9</IdentityThreshold>
			<MinTerminatingSequenceCoverage>0</MinTerminatingSequenceCoverage>
			<PairReadTerminationThreshold>0.1</PairReadTerminationThreshold>
			<MinReadLength>50</MinReadLength>
		</Reassembler>
		<Debug>false</Debug>
    </ConsensusBuilder>
    <Postprocessor>
        <Enabled>true</Enabled>
        <MinFragmentLength>500</MinFragmentLength>
        <MinIdentity>0.99</MinIdentity>
		<MinFragmentCoverage>0.99</MinFragmentCoverage>
        <Debug>false</Debug>
    </Postprocessor>
</config>`

**Comment by gFedonin** [comment]
Hello, Anupriya014!

To use VirGenA you always need a default single reference. Reference selector will try to choose the best (one or more) from the alignment. If it fails or switched off VirGenA will use the default reference from <Reference></Reference> section. It should be one reference, not a list of references. As I understand, viruSITE_genomes.fasta is a multifasta with multiple references. Please keep one and run it again.

Anyway, VirGenA may work very slow for long genomes. How long is your reference?

Sincerely yours,
Gennady.

**Comment by Anupriya014** [comment]
On running T-coffee I got this error -
SEQUENCES TOO LONG [Longuest=2473870][MAX=0][FATAL:T-COFFEE]
So I guess 2473870 is the biggest sequence in Multi-FASTA.

How to choose default single reference? My sample data came from CHO cell line.

**Comment by gFedonin** [comment]
2473870 seems to be too long for VirGenA too...

VirGenA is applicable for the target assembly when you know what you are sequencing and you have reference for it, not just to assemble all viruses or an unknown virus from the sample. If viruSITE_genomes.fasta contains similar genomes - you can pick any of them as default reference. If these genomes are very far from each other - there is no sense to use VirGenA.

What do yo expect to assemble from your data?

**Comment by gFedonin** [comment]
2473870 is too long for viruses... Mimi- and Megaviruses are 1.2-1.3 Mb and you have 2.47 Mb. Are you sure you don't have problems with your fasta?

**Comment by Anupriya014** [comment]
> 2473870 is too long for viruses... Mimi- and Megaviruses are 1.2-1.3 Mb and you have 2.47 Mb. Are you sure you don't have problems with your fasta?

"refseq|NC_022098|2473870nt|Pandoravirus salinus, complete genome" is the one with 2473870 size. I cross-checked in NCBI, looks like correct size  - https://www.ncbi.nlm.nih.gov/nuccore/NC_022098

**Comment by Anupriya014** [comment]
> 2473870 seems to be too long for VirGenA too...
> 
> VirGenA is applicable for the target assembly when you know what you are sequencing and you have reference for it, not just to assemble all viruses or an unknown virus from the sample. If viruSITE_genomes.fasta contains similar genomes - you can pick any of them as default reference. If these genomes are very far from each other - there is no sense to use VirGenA.
> 
> What do yo expect to assemble from your data?

I wished to go for reference assembly over original FASTQs followed by de novo assembly of unplaced reads. The assembled reads were supposed to be aligned with a viral DB then. These all steps are part of virus detection in a sample.

**Comment by gFedonin** [comment]
Sounds rational, but VirGenA can do it only for one reference genome or a set of closely related reference genomes which can be sensibly aligned. In your case you need to use some tool to sort reads to references, like Kraken. Then you can try to use VirGenA to assemble unmaped reads with each portion of reads mapped to each reference found by Kraken separatelly: maybe VirGenA will be able to extend mapped seeds.

Anyway, I recommend not to use VirGenA with Mb length genomes: it might be very slow.

**Comment by Anupriya014** [comment]
> Sounds rational, but VirGenA can do it only for one reference genome or a set of closely related reference genomes which can be sensibly aligned. In your case you need to use some tool to sort reads to references, like Kraken. Then you can try to use VirGenA to assemble unmaped reads with each portion of reads mapped to each reference found by Kraken separatelly: maybe VirGenA will be able to extend mapped seeds.
> 
> Anyway, I recommend not to use VirGenA with Mb length genomes: it might be very slow.

Thanks Gennady . This was helpful.
