### ISSUE TITLE
./res/clusters_reads_0_670.uc (No such file or directory)

### ISSUE THREAD

**Issue by Nicolas-Fernandez** [gFedonin/VirGenA#5]
Dear Gennady G. Fedonin,

First, thank you very much for your tool, that will be very usefull for us :)

I trying toy data set (01_AE, B, C) on MacOS to test installation, with config_test_linux.xml.
I have an error about a missing outputfile, bellow :

################################

me@MacPro:~/VirGenA/release_v1.4$ java -jar VirGenA.jar assemble -c config_test_linux.xml
java.io.FileNotFoundException: ./res/clusters_reads_0_670.uc (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at ReferenceFinder.readClustersAndBuildContigs(ReferenceFinder.java:233)
	at ReferenceFinder.selectReferences(ReferenceFinder.java:545)
	at RefBasedAssembler.assemble(RefBasedAssembler.java:552)
	at RefBasedAssembler.run(RefBasedAssembler.java:663)
	at VirGenA.main(VirGenA.java:34)

################################

./res/ directory is here, whit log.txt :

################################

Creating random reads model from MSA with the parameters given in the config file in <RandomModelParameters>
Creating random reads model from reference with the parameters given in the config file in <RandomModelParameters>
Mapping to MSA stats:
1) Total read pairs: 50000
2) Total pairs with both reads exists: 50000
3) Total reads: 100000
4) Total reads mapped from (3): 1,00, forward: 0,50, reverse: 0,50
5) Total pairs with both reads mapped from (2): 49923, 1,00
6) Concordant pairs from (5): 1,00
7) Total score: 21268249, average score: 212,92
Total time, s: 26
Time: 26
Reads after filtering by length >= 50: 99638
Preprocess time: 0
UClust time: 0

################################

Could you help us please ? :)

Best regards,
Nicolas

**Comment by gFedonin** [comment]
Dear Nicolas-Fernandez,

Thank you for using our tool. As I understand, the problem is that you use linux config file which contains path to linux binary of Vsearch tool (tools directory in the distribution). I recomend to try mac binary from here 

https://github.com/torognes/vsearch/releases

Download it, change the path and try again.

Hope this will help. I've never tried it on mac, but it should work on any java.

P.S. You also need local Blast!

Sincerely yours,
Gennady.

**Comment by Nicolas-Fernandez** [comment]
It's that ! Work fine now 👍 
Install and set path to macos version solved issue, thank you very much !
So used to using linux and not macos ...

I have local Blast, and I have after the error :
Cannot run program "makeblastdb": error=2, No such file or directory
But just add /usr/local/ncbi/blast/bin/ solved also.

Now I can process with our samples.
Have a great day,
Best,
Nicolas
